/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package phoenix;

public class Library {
	public static void main(String[] args) {
		System.err.println("hello   abdou");
	}
    public boolean someLibraryMethod() {
        return true;
    }
}
